version: '4.20.1'


services:

  db:
    image: postgres:12.4-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 5s
      timeout: 3s
      retries: 10
    ports:
      - '5432:5432'
    volumes:
      - diploma_goals_planner_pg_data:/var/lib/postgresql/data/


volumes:
  diploma_goals_planner_pg_data:
