version: '4.20.1'


services:

  db:
    image: postgres:12.4
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - diploma_goals_planner_pg_data:/var/lib/postgresql/data/

  run_migrations:
    image: ${DOCKERHUB_USER}/diploma_goals_planner:latest
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    command: python manage.py migrate

  api:
    image: ${DOCKERHUB_USER}/diploma_goals_planner:latest
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      run_migrations:
        condition: service_completed_successfully

  bot:
    image: ${DOCKERHUB_USER}/diploma_goals_planner:latest
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    command: python manage.py runbot

  collect_static:
    image: ${DOCKERHUB_USER}/diploma_goals_planner:latest
    env_file: .env
    command: python manage.py collectstatic -c --no-input
    volumes:
      - django_static:/opt/app/static/

  frontend:
    image: sermalenk/skypro-front:lesson-38
    restart: on-failure
    ports:
      - "80:80"
    depends_on:
      api:
        condition: service_started
      collect_static:
        condition: service_completed_successfully
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - django_static:/usr/share/nginx/html/static/

volumes:
  diploma_goals_planner_pg_data:
  django_static:
